### ISSUE TITLE
Tahm Kench icon is broken

### ISSUE THREAD

**Issue by MPKohl** [BuddyGG/buddy_frontend#19]

**Comment by simmerkaer** [comment]
What is the broken url? What should it be instead?

**Comment by ecly** [comment]
https://ddragon.leagueoflegends.com/cdn/8.5.2/img/champion/Tahmkench.png

should be

https://ddragon.leagueoflegends.com/cdn/8.5.2/img/champion/TahmKench.png

**Comment by ecly** [comment]
Closed - see v2
